import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations = {
  en: {
    // Header
    'app.title': 'ContentCastAI',
    'app.subtitle': 'AI Content Creator',
    
    // Content Generator
    'content.creator': 'Content Creator',
    'content.aiGeneration': 'AI Generation',
    'content.manualInput': 'Manual Input',
    'content.topic': 'Content Topic',
    'content.topic.placeholder': 'What would you like to create content about?',
    'content.type': 'Content Type',
    'content.type.educational': 'Educational Thread',
    'content.type.news': 'News Update',
    'content.type.personal': 'Personal Story',
    'content.type.analysis': 'Industry Analysis',
    'content.type.creative': 'Creative Story',
    'content.tone': 'Tone',
    'content.tone.professional': 'Professional',
    'content.tone.casual': 'Casual',
    'content.tone.humorous': 'Humorous',
    'content.generate': 'Generate Content',
    'content.generating': 'Generating...',
    
    // Image Selector
    'images.title': 'Image Selection',
    'images.featured': 'Featured Images',
    'images.search': 'Search Images',
    'images.search.placeholder': 'Search for images...',
    'images.uploading': 'Uploading...',
    'images.upload': 'Upload Image',
    'images.select': 'Select Image',
    'images.selected': 'Selected',
    'images.photographer': 'Photo by',
    
    // Content Preview
    'preview.title': 'Content Preview',
    'preview.edit': 'Edit',
    'preview.cancel': 'Cancel',
    'preview.saveChanges': 'Save Changes',
    'preview.yourUsername': 'Your Username',
    'preview.generatedBy': 'Generated by ContentCastAI',
    'preview.reply': 'Reply',
    'preview.recast': 'Recast',
    'preview.like': 'Like',
    'preview.castToFarcaster': 'Cast to Farcaster',
    'preview.publishing': 'Publishing...',
    'preview.connectWallet': 'Connect your wallet to publish content',
    
    // Cast Preparation
    'cast.prepared': 'Cast prepared! Share manually on Farcaster',
    'cast.content': 'Prepared content:',
    'cast.openFarcaster': 'Open in Farcaster and Share',
    'cast.close': 'Close',
    
    // Wallet
    'wallet.connect': 'Connect Wallet',
    'wallet.connecting': 'Connecting...',
    'wallet.connected': 'Wallet Connected',
    'wallet.farcaster': 'Connect with Farcaster Wallet',
    'wallet.coinbase': 'Connect with Coinbase Wallet',
    'wallet.disconnect': 'Disconnect',
    'wallet.fid': 'FID:',
    'wallet.notConnected': 'Not connected',
    'wallet.address': 'Address:',
    'wallet.ensName': 'ENS Name:',
    
    // Recent Activity
    'activity.title': 'Recent Activity',
    'activity.published': 'Published',
    'activity.draftSaved': 'Draft saved',
    'activity.view': 'View →',
    
    // Footer
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.support': 'Support',
    
    // Toasts & Messages
    'toast.contentGenerated': 'Content generated successfully!',
    'toast.castPrepared': 'Cast prepared!',
    'toast.castPreparedDesc': 'You can share manually on Farcaster',
    'toast.walletConnected': 'Wallet Connected',
    'toast.walletDisconnected': 'Wallet Disconnected',
    'toast.connectionFailed': 'Connection Failed',
    'toast.farcasterLinked': 'Farcaster account linked!',
    'toast.farcasterLinkedDesc': 'account automatically linked',

 // ... mevcut anahtarların ...
    'gm.button': 'Daily GM',
    'gm.sending': 'Sending...',
    'gm.sent': 'Sent on-chain GM on Base.',
    'gm.failed': 'Transaction failed',
    
    // Demo Mode
    'demo.indicator': 'Demo Mode: Casts are simulated - Not sent to real Farcaster',
    
    // Language
    'language.switch': 'Switch Language',
    'language.turkish': 'Türkçe',
    'language.english': 'English',
    
    // Quest Page
    'quest.title': 'Quest Center',
    'quest.subtitle': 'Complete quests to earn points and climb the leaderboard',
    'quest.weeklyPoints': 'This Week',
    'quest.currentStreak': 'Daily Streak', 
    'quest.dailyCast': 'Daily Cast',
    'quest.completed': 'Completed',
    'quest.dailyQuests': 'Daily Quests',
    'quest.specialQuests': 'Special Quests',
    'quest.points': 'points',
    'quest.claim': 'Claim',
    'quest.locked': 'Locked',
    'quest.inProgress': 'In Progress',
    'quest.connectWallet': 'Connect Your Wallet',
    'quest.connectWalletDesc': 'Connect your wallet to start earning points and completing quests!',
    'quest.dailyCastDesc': 'Publish content to Farcaster and earn points'
  },
  tr: {
    // Header
    'app.title': 'ContentCastAI',
    'app.subtitle': 'AI İçerik Üretici',
    
    // Content Generator
    'content.creator': 'İçerik Üretici',
    'content.aiGeneration': 'AI Üretimi',
    'content.manualInput': 'Manuel Giriş',
    'content.topic': 'İçerik Konusu',
    'content.topic.placeholder': 'Hangi konu hakkında içerik oluşturmak istiyorsunuz?',
    'content.type': 'İçerik Türü',
    'content.type.educational': 'Eğitici Thread',
    'content.type.news': 'Haber Güncellemesi',
    'content.type.personal': 'Kişisel Hikaye',
    'content.type.analysis': 'Sektör Analizi',
    'content.type.creative': 'Yaratıcı Hikaye',
    'content.tone': 'Ton',
    'content.tone.professional': 'Profesyonel',
    'content.tone.casual': 'Samimi',
    'content.tone.humorous': 'Esprili',
    'content.generate': 'İçerik Üret',
    'content.generating': 'Üretiliyor...',
    
    // Image Selector
    'images.title': 'Görsel Seçimi',
    'images.featured': 'Öne Çıkan Görseller',
    'images.search': 'Görsel Ara',
    'images.search.placeholder': 'Görsel arayın...',
    'images.uploading': 'Yükleniyor...',
    'images.upload': 'Görsel Yükle',
    'images.select': 'Görseli Seç',
    'images.selected': 'Seçildi',
    'images.photographer': 'Fotoğrafçı:',
    
    // Content Preview
    'preview.title': 'İçerik Önizleme',
    'preview.edit': 'Düzenle',
    'preview.cancel': 'İptal',
    'preview.saveChanges': 'Değişiklikleri Kaydet',
    'preview.yourUsername': 'Kullanıcı Adınız',
    'preview.generatedBy': 'ContentCastAI tarafından üretildi',
    'preview.reply': 'Yanıtla',
    'preview.recast': 'Recast',
    'preview.like': 'Beğen',
    'preview.castToFarcaster': 'Farcaster\'a Gönder',
    'preview.publishing': 'Gönderiliyor...',
    'preview.connectWallet': 'İçerik yayınlamak için cüzdanınızı bağlayın',
    
    // Cast Preparation
    'cast.prepared': 'Cast hazırlandı! Manuel olarak Farcaster\'da paylaşın',
    'cast.content': 'Hazırlanan içerik:',
    'cast.openFarcaster': 'Farcaster\'da Aç ve Paylaş',
    'cast.close': 'Kapat',
    
    // Wallet
    'wallet.connect': 'Cüzdan Bağla',
    'wallet.connecting': 'Bağlanıyor...',
    'wallet.connected': 'Cüzdan Bağlandı',
    'wallet.farcaster': 'Farcaster Cüzdanı ile Bağlan',
    'wallet.coinbase': 'Coinbase Cüzdanı ile Bağlan',
    'wallet.disconnect': 'Bağlantıyı Kes',
    'wallet.fid': 'FID:',
    'wallet.notConnected': 'Bağlı değil',
    'wallet.address': 'Adres:',
    'wallet.ensName': 'ENS Adı:',
    
    // Recent Activity
    'activity.title': 'Son Aktiviteler',
    'activity.published': 'Yayınlandı',
    'activity.draftSaved': 'Taslak kaydedildi',
    'activity.view': 'Görüntüle →',
    
    // Footer
    'footer.privacy': 'Gizlilik',
    'footer.terms': 'Şartlar',
    'footer.support': 'Destek',
    
    // Toasts & Messages
    'toast.contentGenerated': 'İçerik başarıyla üretildi!',
    'toast.castPrepared': 'Cast hazırlandı!',
    'toast.castPreparedDesc': 'Farcaster\'da manuel olarak paylaşabilirsiniz',
    'toast.walletConnected': 'Cüzdan Bağlandı',
    'toast.walletDisconnected': 'Cüzdan Bağlantısı Kesildi',
    'toast.connectionFailed': 'Bağlantı Başarısız',
    'toast.farcasterLinked': 'Farcaster hesabı bağlandı!',
    'toast.farcasterLinkedDesc': 'hesabınız otomatik olarak bağlandı',

// ... mevcut anahtarların ...
    'gm.button': 'Günlük GM',
    'gm.sending': 'Gönderiliyor...',
    'gm.sent': 'Base ağında on-chain GM gönderildi.',
    'gm.failed': 'İşlem başarısız',
    
    // Demo Mode
    'demo.indicator': 'Demo Modu: Cast\'ler simüle ediliyor - Gerçek Farcaster\'a gönderilmiyor',
    
    // Language
    'language.switch': 'Dil Değiştir',
    'language.turkish': 'Türkçe',
    'language.english': 'English',
    
    // Quest Page
    'quest.title': 'Görev Merkezi',
    'quest.subtitle': 'Görevleri tamamlayarak puan kazan ve liderlik tablosunda yüksel',
    'quest.weeklyPoints': 'Bu Hafta',
    'quest.currentStreak': 'Günlük Seri',
    'quest.dailyCast': 'Günlük Cast',
    'quest.completed': 'Tamamlandı',
    'quest.dailyQuests': 'Günlük Görevler',
    'quest.specialQuests': 'Özel Görevler',
    'quest.points': 'puan',
    'quest.claim': 'Al',
    'quest.locked': 'Kilitli',
    'quest.inProgress': 'Devam Ediyor',
    'quest.connectWallet': 'Cüzdanını Bağla',
    'quest.connectWalletDesc': 'Puan kazanmaya ve görevleri tamamlamaya başlamak için cüzdanını bağla!',
    'quest.dailyCastDesc': 'Farcaster\'a içerik yayınla ve puan kazan'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('contentcastai-language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('contentcastai-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};