import { createContext, useContext, useState, useEffect, ReactNode } from "react";

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'app.title': 'ContentCastAI',
    'app.subtitle': 'AI Content Creator',
    'header.theme': 'Theme',
    'header.shop': 'Shop', 
    'header.about': 'About',
    'header.language': 'Language',
    'wallet.connect': 'Connect Wallet',
    'wallet.connecting': 'Connecting...',
    'wallet.connected': 'Wallet Connected',
    'wallet.disconnect': 'Disconnect',
    'wallet.viewProfile': 'View Profile',
    'wallet.copyAddress': 'Copy Address',
    'wallet.ensName': 'ENS Name',
    'wallet.address': 'Wallet Address',
    'wallet.balance': 'Balance',
    'wallet.connectWithFarcaster': 'Connect with Farcaster',
    'wallet.connectWithCoinbase': 'Connect with Coinbase Wallet',
    'wallet.farcasterDescription': 'Use your Farcaster identity',
    'wallet.coinbaseDescription': 'Use Coinbase Wallet app',
    'wallet.chooseWallet': 'Choose a wallet to connect and access the ContentCastAI platform',
    'wallet.farcasterConnected': 'Farcaster Wallet',
    'wallet.farcasterConnectedDesc': 'Connected with Farcaster wallet',
    'wallet.coinbaseConnected': 'Coinbase Wallet',
    'wallet.coinbaseConnectedDesc': 'Connected with Coinbase wallet',
    'wallet.baseappConnected': 'BaseApp Wallet Connected',
    'wallet.baseappConnectedDesc': 'Connected with BaseApp wallet',
    'wallet.connectionFailed': 'Connection Failed',
    'wallet.connectionFailedDesc': 'Please make sure you have a Web3 wallet installed and try again',
    'wallet.coinbaseFailedDesc': 'Please make sure you have Coinbase Wallet installed and try again',
    'wallet.disconnected': 'Wallet Disconnected',
    'wallet.disconnectedDesc': 'Your wallet has been disconnected',
    'wallet.unknown': 'Unknown',
    'wallet.connectYourWallet': 'Connect Your Wallet',
    'wallet.chooseWalletToConnect': 'Choose a wallet to connect and access the ContentCastAI platform',
    'wallet.farcaster': 'Farcaster',
    'wallet.baseapp': 'BaseApp Wallet',
    'wallet.connectWallet': 'Connect wallet',
    'wallet.coinbaseWallet': 'Coinbase Wallet',
    'wallet.connectUsingCoinbase': 'Connect using Coinbase Wallet',
    'wallet.termsOfService': 'By connecting your wallet, you agree to our Terms of Service',
    'wallet.aiContentRequiresWallet': 'AI Content Requires Wallet',
    'wallet.connectWalletToCastAI': 'Please connect your wallet to cast AI-generated content',
    'wallet.farcasterLinked': 'Farcaster Account Linked',
    'wallet.farcasterLinkedDesc': '@{username} account has been automatically linked',
    'wallet.displayName': 'Display Name',
    'wallet.username': 'Username',
    'wallet.farcasterID': 'Farcaster ID',
    'wallet.connectionCancelled': 'Connection Cancelled',
    'wallet.connectionCancelledDesc': 'Wallet connection was cancelled by user',
    'wallet.connectionTimeout': 'Connection Timeout',
    'wallet.connectionTimeoutDesc': 'Wallet connection timed out. Please try again.',
    'wallet.noWalletFound': 'No Wallet Found',
    'wallet.installWallet': 'Please install MetaMask, Rabby, or another Web3 wallet',
    'wallet.connectedDesc': 'Your wallet has been connected successfully',
    'content.generate': 'Generate Content',
    'content.preparing': 'Preparing...',
    'content.prepare': 'Prepare Cast',
    'content.openFarcaster': 'Open in Farcaster',
    'content.close': 'Close',
    'content.readyToPost': 'Cast ready! Share manually on Farcaster',
    'content.topic': 'Topic',
    'content.topicPlaceholder': 'What would you like to create content about?',
    'content.contentType': 'Content Type',
    'content.tone': 'Tone',
    'content.suggestions.title': 'Quick Suggestions',
    'content.suggestions.dailyQuote': 'Daily Quote',
    'content.suggestions.baseToken': 'Base Token',
    'content.suggestions.farcasterInfo': 'What is Farcaster?',
    'content.suggestions.cryptoNews': 'Crypto News',
    'content.suggestions.defiTrends': 'DeFi Trends',
    'content.suggestions.aiTech': 'AI Technology',
    'content.suggestions.nftTrends': 'NFT Trends',
    'content.suggestions.web3Gaming': 'Web3 Gaming',
    'content.suggestions.goodMorning': 'Good Morning',
    'content.suggestions.goodNight': 'Good Night',
    'content.suggestions.football': 'Football ⚽',
    'content.suggestions.trendingTopics': 'Trending 🔥',
    'content.generator': 'Content Generator',
    'content.aiGeneration': 'AI Generation',
    'content.manualInput': 'Manual Input',
    'content.yourContent': 'Your Content',
    'content.manualInput.placeholder': 'Write your content here...\n\nYou can create:\n• Thread posts with numbered points (1/, 2/, 3/)\n• News updates and analysis\n• Personal stories and experiences\n• Educational content\n• Creative writing\n\nTip: Use emojis and line breaks for better readability!',
    'content.topic.placeholder': 'What would you like to create content about?',
    'content.type': 'Content Type',
    'content.edit': 'Edit',
    'content.save': 'Save',
    'content.cancel': 'Cancel',
    'content.characters': 'characters',
    'content.readyToUse': 'Ready to use',
    'content.useThisContent': 'Use This Content',
    'content.preview': 'Content Preview',
    'content.saveChanges': 'Save Changes',
    'content.prepareCast': 'Prepare Cast',
    'content.castPrepared': 'Cast prepared!',
    'content.shareManually': 'Share manually on Farcaster',
    'content.castOpened': 'Cast opened!',
    'content.nativeFarcasterOpened': 'Native Farcaster compose opened',
    'content.preparedContent': 'Prepared content:',
    'content.noContentToPrepare': 'No content to prepare',
    'content.generateContentFirst': 'Please generate content before preparing cast',
    'content.publishingFailed': 'Publishing failed',
    'content.failedToPublish': 'Failed to publish content to Farcaster',
    'content.dailyLimitReached': 'Daily cast limit reached',
    'content.dailyLimitDescription': 'You can cast a maximum of {maxDailyCasts} times per day. Today you have cast {count} times.',
    'content.dailyCastStatus': 'Daily Cast Status',
    'content.remaining': 'remaining',
    'content.contentUpdated': 'Content updated',
    'content.changesSaved': 'Your changes have been saved',
    'content.reply': 'Reply',
    'content.recast': 'Recast',
    'content.like': 'Like',
    'toast.contentGenerated': 'Content Generated',
    'toast.contentReady': 'Your AI-powered content is ready for review',
    'toast.tryAgainLater': 'Please try again later.',
    'toast.quotaExceeded': 'AI API quota exceeded',
    'toast.quotaExceededDesc': 'Please check your AI API billing or try the manual content creation mode.',
    'toast.configIssue': 'AI API configuration issue',
    'toast.configIssueDesc': 'Please check your API key configuration.',
    'toast.tooManyRequests': 'Too many requests',
    'toast.tooManyRequestsDesc': 'Please wait a moment and try again.',
    'toast.failedToGenerate': 'Failed to generate content',
    'toast.draftSaved': 'Draft saved',
    'toast.draftSavedDesc': 'Your content has been saved as a draft',
    'toast.saveFailed': 'Save failed',
    'toast.saveFailedDesc': 'Failed to save draft',
    'toast.topicRequired': 'Topic required',
    'toast.topicRequiredDesc': 'Please enter a topic for content generation',
    'toast.contentTypeRequired': 'Content type required',
    'toast.contentTypeRequiredDesc': 'Please select a content type',
    'toast.contentRequired': 'Content required',
    'toast.contentRequiredDesc': 'Please enter some content',
    'toast.contentTooShort': 'Content too short',
    'toast.contentTooShortDesc': 'Content must be at least 10 characters',
    'toast.manualContentReady': 'Content ready!',
    'toast.manualContentReadyDesc': 'Your manual content is ready for review',
    'button.saving': 'Saving...',
    'button.saveAsDraft': 'Save as Draft',
    'content.generatedContentPlaceholder': 'Generated content will appear here...',
    'content.editPlaceholder': 'Edit your content here...',
    'content.recent': 'Recent Activity',
    'content.published': 'Published',
    'content.view': 'View',
    'image.producer': 'Image Producer',
    'image.selected': 'Image Selected',
    'image.uploadedSelected': 'Uploaded image selected',
    'image.stockPhotoSelected': 'Stock photo selected',
    'image.stockPhotos': 'Stock Photos',
    'image.uploadImage': 'Upload Image',
    'image.searchStockPhotos': 'Search Stock Photos',
    'image.searchPlaceholder': 'Search for images...',
    'image.clickToUpload': 'Click to upload images',
    'image.noUploadedImages': 'No uploaded images yet',
    'image.uploadYourImages': 'Upload Your Images',
    'image.searchRequired': 'Search query required',
    'image.enterSearchTerm': 'Please enter a search term',
    'image.invalidFileType': 'Invalid file type',
    'image.uploadImageFile': 'Please upload an image file (JPG, PNG, GIF, etc.)',
    'image.fileTooLarge': 'File too large',
    'image.uploadSmaller10MB': 'Please upload an image smaller than 10MB',
    'image.imageUploaded': 'Image uploaded',
    'footer.poweredBy': 'Powered by Gemini AI & Pexels',
    'preview.yourUsername': 'Your Username',
    'preview.now': 'now',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'settings': 'Settings',
    'comingSoon': 'Coming soon...',
    'aboutDescription': 'ContentCastAI - AI-powered content creation for Farcaster',
    'navigation.home': 'Home',
    'navigation.quest': 'Quest',
    'navigation.leaderboard': 'Leaderboard',
    'navigation.rewards': 'Rewards',
    'navigation.profile': 'Profile',
    'profile.connectWallet': 'Connect Your Wallet',
    'profile.connectWalletDesc': 'Connect your wallet to view your profile',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.about': 'About',
    'profile.userAnalytics': 'User Analytics',
    'profile.analyticsWip': 'Work in progress... New features coming this week.',
    'quest.title': 'Quest Center',
    'quest.subtitle': 'Complete quests to earn points and climb the leaderboard',
    'quest.totalPoints': 'Total Points',
    'quest.currentStreak': 'Day Streak',
    'quest.weeklyPoints': 'This Week',
    'quest.completed': 'Completed',
    'quest.dailyQuests': 'Daily Quests',
    'quest.specialQuests': 'Special Quests',
    'quest.dailyCheckIn': 'Daily Check-in',
    'quest.dailyCheckInDesc': 'Visit the app daily to maintain your streak',
    'quest.dailyCast': 'Daily Cast',
    'quest.dailyCastDesc': 'Publish content to Farcaster and earn points',
    'quest.totalCast': 'Total Cast',
    'quest.sendGmDaily': 'Send GM Daily',
    'quest.sendGmDailyDesc': 'Open GMonchain miniapp and send your GM to the another chain!',
    'quest.castNow': 'Cast Now 📡',
    'quest.nextCheckIn': 'Next check-in available in',
    'quest.shareApp': 'Share ContentCastAI',
    'quest.shareAppDesc': '🚀 Share quality content and complete daily quests to earn rewards!',
    'quest.shareNow': 'Share Now 🎉',
    'quest.nftHolding': 'NFT Holder',
    'quest.nftHoldingDesc': 'Hold our special NFT to earn bonus points',
    'quest.points': 'points',
    'quest.claim': 'Claim',
    'quest.locked': 'Locked',
    'quest.inProgress': 'In Progress',
    'quest.connectWallet': 'Connect Your Wallet',
    'quest.connectWalletDesc': 'Connect your wallet to start earning points and completing quests!',
    'quest.dailyCheckInComplete': 'Daily Check-in Complete!',
    'quest.questCompleted': 'Quest Completed! 🎉',
    'quest.questFailed': 'Quest Failed',
    'quest.earnedPoints': 'You earned {points} point{plural}!',
    'quest.bonusQuests': 'Bonus Quests',
    'quest.bonusQuestsDesc': 'One-time bonus tasks to earn extra points',
    'quest.followFarcaster': 'Follow on Farcaster',
    'quest.followFarcasterDesc': 'Follow @mrrobotcrypto.eth on Farcaster',
    'quest.followX': 'Follow on X',
    'quest.followXDesc': 'Follow @MrRobotKripto on X (Twitter)',
    'quest.addMiniApp': 'Add Mini App',
    'quest.addMiniAppDesc': 'Add ContentCastAI to your app list',
    'quest.follow': 'Follow',
    'quest.addToApps': 'Add to Apps',
    'quest.completeTask': 'Complete Task',
    'quest.progress': 'Progress',
    'quest.oneTimeQuests': 'One-Time Quests',
    'quest.addNow': 'Add Now',
    'quest.walletRequired': 'Wallet Required',
    'leaderboard.title': 'Leaderboard',
    'leaderboard.subtitle': 'Compete with other users and climb to the top',
    'leaderboard.weekly': '7 Days',
    'leaderboard.monthly': '1 Month',
    'leaderboard.quarterly': '3 Months',
    'leaderboard.yearly': '1 Year',
    'leaderboard.yourPosition': 'Your Position',
    'leaderboard.points': 'points',
    'leaderboard.topPlayers': 'Top Players',
    'leaderboard.fullRankings': 'Full Rankings',
    'leaderboard.user': 'User',
    'leaderboard.weeklyPoints': 'This Week',
    'leaderboard.dailyStreak': 'Daily Streak',
    'leaderboard.dailyCasts': 'Daily Casts',
    'leaderboard.completed': 'Completed',
    'leaderboard.casts': 'casts',
    'leaderboard.quests': 'quests',
    'rewards.title': 'My Rewards',
    'rewards.subtitle': 'Claim your earned DEGEN tokens based on your quest points',
    'rewards.connectWallet': 'Connect Your Wallet',
    'rewards.connectWalletDesc': 'Connect your wallet to view and claim your DEGEN rewards!',
    'rewards.totalPoints': 'Total Points',
    'rewards.claimableDegen': 'Claimable DEGEN',
    'rewards.degenPerPoint': 'DEGEN per Point',
    'rewards.degenClaim': 'DEGEN Token Claim',
    'rewards.howItWorks': 'How it works:',
    'rewards.rule1': '1 Quest Point = 0.1 DEGEN Token',
    'rewards.rule2': 'Minimum 250 points required to claim',
    'rewards.rule3': 'Claim all your accumulated DEGEN at once',
    'rewards.rule4': 'Points are reset after claiming',
    'rewards.readyToClaim': 'You can claim {amount} DEGEN tokens!',
    'rewards.needMorePoints': 'You need {amount} more points to claim DEGEN',
    'rewards.completeQuests': 'Complete daily quests to earn more points!',
    'rewards.progress': 'Progress to Next Claim',
    'leaderboard.streak': 'Streak',
    'leaderboard.days': 'days',
    'leaderboard.you': 'You',
    'leaderboard.connectWallet': 'Connect Your Wallet',
    'leaderboard.connectWalletDesc': 'Connect your wallet to see your position on the leaderboard!',
    'leaderboard.share': 'Share Position',
    'leaderboard.sharing': 'Sharing...',
    'leaderboard.previous': 'Previous',
    'leaderboard.next': 'Next',
    'header.feedback': 'Feedback',
    'menu.goToAbout': 'Learn More About ContentCastAI',
    'menu.sendFeedback': 'Send Feedback',
    'about.title': 'About ContentCastAI',
    'about.subtitle': 'AI-powered content creation for the decentralized social web',
    'about.what.title': 'What is ContentCastAI?',
    'about.what.desc1': 'ContentCastAI is an innovative platform that combines the power of artificial intelligence with the decentralized social network Farcaster. Our mission is to help creators, marketers, and everyday users generate engaging, high-quality content effortlessly.',
    'about.what.desc2': 'With features like AI-powered content generation, curated stock photography integration, gamification through quests and leaderboards, and multi-language support, ContentCastAI makes content creation accessible and fun for everyone.',
    'about.features.title': 'Key Features',
    'about.feature1.title': 'AI-Powered Content',
    'about.feature1.desc': 'Generate engaging social media content with advanced AI technology',
    'about.feature2.title': 'Farcaster Integration',
    'about.feature2.desc': 'Seamlessly publish your content to the decentralized social network',
    'about.feature3.title': 'Quest System',
    'about.feature3.desc': 'Earn points, maintain streaks, and climb the leaderboard',
    'about.developer.title': 'Developer',
    'about.developer.desc': 'ContentCastAI was developed with passion for Web3, decentralized social networks, and AI technology. Built to empower creators in the new era of social media.',
    'about.connect': 'Connect with the Developer:',
    'about.tech.title': 'Technology Stack',
    'about.version': 'Version',
    'about.builtWith': 'Built with',
    'about.forWeb3': 'for the Web3 community',
    'about.donate.title': 'Support the Project',
    'about.donate.desc': 'Help us continue developing ContentCastAI by sending donations to:',
    'about.donate.address': 'mrrobotcrypto.eth',
    'about.copied': 'Copied to clipboard!',
    'about.copiedDesc': 'copied successfully',
    'about.copyFailed': 'Copy failed',
    'about.copyFailedDesc': 'Please copy manually',
    'countdown.resetIn': 'Reset in',
    'countdown.resetAvailable': 'Reset available!',
    'wallet.balances': 'Balances',
    'home.recentActivity': 'Recent Activity',
    'home.shareApp': 'Share ContentCastAI',
    'home.shareAppDesc': 'Earn 1 point daily by sharing the app',
    'feedback.title': 'Feedback',
    'feedback.subtitle': 'Help us improve ContentCastAI by sharing your thoughts, reporting bugs, or suggesting new features',
    'feedback.typeLabel': 'Feedback Type',
    'feedback.typePlaceholder': 'Select feedback type...',
    'feedback.messageLabel': 'Your Message',
    'feedback.messagePlaceholder': 'Please describe your feedback in detail. Be specific about any issues, suggestions, or compliments you would like to share...',
    'feedback.minLength': 'Minimum 10 characters',
    'feedback.send': 'Send Feedback',
    'feedback.sending': 'Sending...',
    'feedback.success': 'Feedback Sent!',
    'feedback.successDesc': 'Thank you for your feedback. We appreciate your input!',
    'feedback.error': 'Error',
    'feedback.errorDesc': 'Failed to send feedback. Please try again.',
    'feedback.typeRequired': 'Feedback Type Required',
    'feedback.typeRequiredDesc': 'Please select a feedback type',
    'feedback.messageRequired': 'Message Required',
    'feedback.messageRequiredDesc': 'Please enter your feedback message',
    'feedback.messageTooShort': 'Message Too Short',
    'feedback.messageTooShortDesc': 'Please provide more detailed feedback (at least 10 characters)',
    'feedback.thankYou': 'Thank You!',
    'feedback.thankYouDesc': 'Your feedback has been sent successfully. We really appreciate your input and will review it carefully.',
    'feedback.sendMore': 'Send More Feedback',
    'feedback.types.bug': 'Bug Report',
    'feedback.types.bugDesc': 'Report a problem or error',
    'feedback.types.feature': 'Feature Request',
    'feedback.types.featureDesc': 'Suggest a new feature or improvement',
    'feedback.types.general': 'General Feedback',
    'feedback.types.generalDesc': 'Share your thoughts or suggestions',
    'feedback.types.compliment': 'Compliment',
    'feedback.types.complimentDesc': 'Share what you love about the app',
    'feedback.guidelines.title': 'Feedback Guidelines',
    'feedback.guidelines.bugs': 'Bug Reports:',
    'feedback.guidelines.bugsDesc': 'Please include detailed steps to reproduce the issue and your browser information.',
    'feedback.guidelines.features': 'Feature Requests:',
    'feedback.guidelines.featuresDesc': 'Explain how the feature would benefit you and other users.',
    'feedback.guidelines.general': 'General Feedback:',
    'feedback.guidelines.generalDesc': 'Share your overall experience and suggestions for improvement.'
  },
  tr: {
    'app.title': 'ContentCastAI',
    'app.subtitle': 'AI İçerik Üreticisi',
    'header.theme': 'Tema',
    'header.shop': 'Mağaza',
    'header.about': 'Hakkında', 
    'header.language': 'Dil',
    'wallet.connect': 'Cüzdan Bağla',
    'wallet.connecting': 'Bağlanıyor...',
    'wallet.connected': 'Cüzdan Bağlandı',
    'wallet.disconnect': 'Bağlantıyı Kes',
    'wallet.viewProfile': 'Profili Görüntüle',
    'wallet.copyAddress': 'Adresi Kopyala',
    'wallet.ensName': 'ENS Adı',
    'wallet.address': 'Cüzdan Adresi',
    'wallet.balance': 'Bakiye',
    'wallet.connectWithFarcaster': 'Farcaster ile Bağlan',
    'wallet.connectWithCoinbase': 'Coinbase Wallet ile Bağlan',
    'wallet.farcasterDescription': 'Farcaster kimliğinizi kullanın',
    'wallet.coinbaseDescription': 'Coinbase Wallet uygulamasını kullanın',
    'wallet.chooseWallet': 'ContentCastAI platformuna erişmek için bir cüzdan seçin',
    'wallet.farcasterConnected': 'Farcaster Cüzdanı',
    'wallet.farcasterConnectedDesc': 'Farcaster cüzdanı ile bağlandı',
    'wallet.coinbaseConnected': 'Coinbase Cüzdanı',
    'wallet.coinbaseConnectedDesc': 'Coinbase cüzdanı ile bağlandı',
    'wallet.baseappConnected': 'BaseApp Cüzdanı Bağlandı',
    'wallet.baseappConnectedDesc': 'BaseApp cüzdanı ile bağlandı',
    'wallet.connectionFailed': 'Bağlantı Başarısız',
    'wallet.connectionFailedDesc': 'Lütfen Web3 cüzdanınızın yüklü olduğundan emin olun ve tekrar deneyin',
    'wallet.coinbaseFailedDesc': 'Lütfen Coinbase Wallet uygulamasının yüklü olduğundan emin olun ve tekrar deneyin',
    'wallet.disconnected': 'Cüzdan Bağlantısı Kesildi',
    'wallet.disconnectedDesc': 'Cüzdanınızın bağlantısı kesildi',
    'wallet.unknown': 'Bilinmeyen',
    'wallet.connectYourWallet': 'Cüzdanınızı Bağlayın',
    'wallet.chooseWalletToConnect': 'ContentCastAI platformuna erişmek için bir cüzdan seçin',
    'wallet.farcaster': 'Farcaster',
    'wallet.baseapp': 'BaseApp Wallet',
    'wallet.connectWallet': 'Cüzdan bağla',
    'wallet.coinbaseWallet': 'Coinbase Wallet',
    'wallet.connectUsingCoinbase': 'Coinbase Wallet kullanarak bağlan',
    'wallet.termsOfService': 'Cüzdanınızı bağlayarak Hizmet Şartlarımızı kabul etmiş olursunuz',
    'wallet.aiContentRequiresWallet': 'AI İçerik Cüzdan Gerektiriyor',
    'wallet.connectWalletToCastAI': 'AI ile üretilen içeriği paylaşmak için lütfen cüzdanınızı bağlayın',
    'wallet.farcasterLinked': 'Farcaster Hesabı Bağlandı',
    'wallet.farcasterLinkedDesc': '@{username} hesabınız otomatik olarak bağlandı',
    'wallet.displayName': 'Görünen Ad',
    'wallet.username': 'Kullanıcı Adı',
    'wallet.farcasterID': 'Farcaster ID',
    'wallet.connectionCancelled': 'Bağlantı İptal Edildi',
    'wallet.connectionCancelledDesc': 'Cüzdan bağlantısı kullanıcı tarafından iptal edildi',
    'wallet.connectionTimeout': 'Bağlantı Zaman Aşımı',
    'wallet.connectionTimeoutDesc': 'Cüzdan bağlantısı zaman aşımına uğradı. Lütfen tekrar deneyin.',
    'wallet.noWalletFound': 'Cüzdan Bulunamadı',
    'wallet.installWallet': 'Lütfen MetaMask, Rabby veya başka bir Web3 cüzdanı yükleyin',
    'wallet.connectedDesc': 'Cüzdanınız başarıyla bağlandı',
    'content.generate': 'İçerik Üret',
    'content.preparing': 'Hazırlanıyor...',
    'content.prepare': 'Cast Hazırla', 
    'content.openFarcaster': 'Farcaster\'da Aç',
    'content.close': 'Kapat',
    'content.readyToPost': 'Cast hazırlandı! Farcaster\'da manuel olarak paylaşın',
    'content.topic': 'Konu',
    'content.topicPlaceholder': 'Hangi konuda içerik oluşturmak istiyorsunuz?',
    'content.contentType': 'İçerik Türü',
    'content.tone': 'Ton',
    'content.suggestions.title': 'Hızlı Öneriler',
    'content.suggestions.dailyQuote': 'Günün Sözü',
    'content.suggestions.baseToken': 'Base Token',
    'content.suggestions.farcasterInfo': 'Farcaster Nedir?',
    'content.suggestions.cryptoNews': 'Kripto Haberleri',
    'content.suggestions.defiTrends': 'DeFi Trendleri',
    'content.suggestions.aiTech': 'AI Teknolojisi',
    'content.suggestions.nftTrends': 'NFT Trendleri',
    'content.suggestions.web3Gaming': 'Web3 Oyunları',
    'content.suggestions.goodMorning': 'Günaydın',
    'content.suggestions.goodNight': 'İyi Geceler',
    'content.suggestions.football': 'Futbol ⚽',
    'content.suggestions.trendingTopics': 'Trendler 🔥',
    'content.generator': 'İçerik Üreticisi',
    'content.aiGeneration': 'AI Üretimi',
    'content.manualInput': 'Manuel Giriş',
    'content.yourContent': 'İçeriğiniz',
    'content.manualInput.placeholder': 'İçeriğinizi buraya yazın...\n\nŞunları oluşturabilirsiniz:\n• Numaralı konulu gönderiler (1/, 2/, 3/)\n• Haber güncellemeleri ve analizler\n• Kişisel hikayeler ve deneyimler\n• Eğitici içerik\n• Yaratıcı yazılar\n\nİpucu: Daha iyi okunabilirlik için emoji ve satır arası kullanın!',
    'content.topic.placeholder': 'Hangi konuda içerik oluşturmak istiyorsunuz?',
    'content.type': 'İçerik Türü',
    'content.edit': 'Düzenle',
    'content.save': 'Kaydet',
    'content.cancel': 'İptal',
    'content.characters': 'karakter',
    'content.readyToUse': 'Kullanıma hazır',
    'content.useThisContent': 'Bu İçeriği Kullan',
    'content.preview': 'İçerik Önizleme',
    'content.saveChanges': 'Değişiklikleri Kaydet',
    'content.prepareCast': 'Cast Hazırla',
    'content.castPrepared': 'Cast hazırlandı!',
    'content.shareManually': 'Manuel olarak Farcaster\'da paylaşın',
    'content.castOpened': 'Cast açıldı!',
    'content.nativeFarcasterOpened': 'Native Farcaster compose açıldı',
    'content.preparedContent': 'Hazırlanan içerik:',
    'content.noContentToPrepare': 'Hazırlanacak içerik yok',
    'content.generateContentFirst': 'Lütfen cast hazırlamadan önce içerik oluşturun',
    'content.publishingFailed': 'Yayınlama başarısız',
    'content.failedToPublish': 'İçeriği Farcaster\'a yayınlama başarısız oldu',
    'content.dailyLimitReached': 'Günlük cast limitiniz dolmuştur',
    'content.dailyLimitDescription': 'Günde maksimum {maxDailyCasts} cast atabilirsiniz. Bugün {count} cast attınız.',
    'content.dailyCastStatus': 'Günlük Cast Durumu',
    'content.remaining': 'kalan',
    'content.contentUpdated': 'İçerik güncellendi',
    'content.changesSaved': 'Değişiklikleriniz kaydedildi',
    'content.reply': 'Yanıtla',
    'content.recast': 'Yeniden Yayınla',
    'content.like': 'Beğen',
    'toast.contentGenerated': 'İçerik Oluşturuldu',
    'toast.contentReady': 'AI destekli içeriğiniz inceleme için hazır',
    'toast.tryAgainLater': 'Lütfen daha sonra tekrar deneyin.',
    'toast.quotaExceeded': 'AI API kotası aşıldı',
    'toast.quotaExceededDesc': 'Lütfen AI API faturalanıznızı kontrol edin veya manuel içerik oluşturma modunu deneyin.',
    'toast.configIssue': 'AI API yapılandırma sorunu',
    'toast.configIssueDesc': 'Lütfen API anahtarı yapılandırmanızı kontrol edin.',
    'toast.tooManyRequests': 'Çok fazla istek',
    'toast.tooManyRequestsDesc': 'Lütfen bir dakika bekleyin ve tekrar deneyin.',
    'toast.failedToGenerate': 'İçerik oluşturma başarısız',
    'toast.draftSaved': 'Taslak kaydedildi',
    'toast.draftSavedDesc': 'İçeriğiniz taslak olarak kaydedildi',
    'toast.saveFailed': 'Kaydetme başarısız',
    'toast.saveFailedDesc': 'Taslak kaydedilemedi',
    'toast.topicRequired': 'Konu gerekli',
    'toast.topicRequiredDesc': 'Lütfen içerik oluşturma için bir konu girin',
    'toast.contentTypeRequired': 'İçerik türü gerekli',
    'toast.contentTypeRequiredDesc': 'Lütfen bir içerik türü seçin',
    'toast.contentRequired': 'İçerik gerekli',
    'toast.contentRequiredDesc': 'Lütfen biraz içerik girin',
    'toast.contentTooShort': 'İçerik çok kısa',
    'toast.contentTooShortDesc': 'İçerik en az 10 karakter olmalıdır',
    'toast.manualContentReady': 'İçerik hazır!',
    'toast.manualContentReadyDesc': 'Manuel içeriğiniz inceleme için hazır',
    'button.saving': 'Kaydediliyor...',
    'button.saveAsDraft': 'Taslak Olarak Kaydet',
    'content.generatedContentPlaceholder': 'Oluşturulan içerik burada görünecek...',
    'content.editPlaceholder': 'İçeriğinizi buraya düzenleyin...',
    'content.recent': 'Son Aktiviteler',
    'content.published': 'Yayınlandı',
    'content.view': 'Görüntüle',
    'image.producer': 'Resim Üreticisi',
    'image.selected': 'Resim Seçildi',
    'image.uploadedSelected': 'Yüklenen resim seçildi',
    'image.stockPhotoSelected': 'Stok fotoğraf seçildi',
    'image.stockPhotos': 'Stok Fotoğraflar',
    'image.uploadImage': 'Resim Yükle',
    'image.searchStockPhotos': 'Stok Fotoğraf Ara',
    'image.searchPlaceholder': 'Resim ara...',
    'image.clickToUpload': 'Resimleri yüklemek için tıklayın',
    'image.noUploadedImages': 'Henüz yüklenmiş resim yok',
    'image.uploadYourImages': 'Resimlerinizi Yükleyin',
    'image.searchRequired': 'Arama sorgusu gerekli',
    'image.enterSearchTerm': 'Lütfen bir arama terimi girin',
    'image.invalidFileType': 'Geçersiz dosya türü',
    'image.uploadImageFile': 'Lütfen bir resim dosyası yükleyin (JPG, PNG, GIF, vb.)',
    'image.fileTooLarge': 'Dosya çok büyük',
    'image.uploadSmaller10MB': 'Lütfen 10MB\'dan küçük bir resim yükleyin',
    'image.imageUploaded': 'Resim yüklendi',
    'footer.poweredBy': 'Gemini AI ve Pexels tarafından desteklenmektedir',
    'preview.yourUsername': 'Kullanıcı Adınız',
    'preview.now': 'şimdi',
    'theme.light': 'Açık',
    'theme.dark': 'Koyu',
    'settings': 'Ayarlar',
    'comingSoon': 'Yakında...',
    'aboutDescription': 'ContentCastAI - Farcaster için AI destekli içerik oluşturma',
    'navigation.home': 'Ana Sayfa',
    'navigation.quest': 'Görevler',
    'navigation.leaderboard': 'Liderlik Tablosu',
    'navigation.rewards': 'Kazançlarım',
    'navigation.profile': 'Profilim',
    'profile.connectWallet': 'Cüzdanınızı Bağlayın',
    'profile.connectWalletDesc': 'Profilinizi görüntülemek için cüzdanınızı bağlayın',
    'profile.followers': 'Takipçi',
    'profile.following': 'Takip Edilen',
    'profile.about': 'Hakkında',
    'profile.userAnalytics': 'Kullanıcı Analizi',
    'profile.analyticsWip': 'Çalışmalar devam ediyor... Bu hafta yeni eklemeler yapılacak.',
    'quest.title': 'Görev Merkezi',
    'quest.subtitle': 'Görevleri tamamlayarak puan kazanın ve liderlik tablosunda yükselin',
    'quest.totalPoints': 'Toplam Puan',
    'quest.currentStreak': 'Günlük Seri',
    'quest.weeklyPoints': 'Bu Hafta',
    'quest.completed': 'Tamamlandı',
    'quest.dailyQuests': 'Günlük Görevler',
    'quest.specialQuests': 'Özel Görevler',
    'quest.dailyCheckIn': 'Günlük Giriş',
    'quest.dailyCheckInDesc': 'Serinizi korumak için uygulamayı her gün ziyaret edin',
    'quest.nftHolding': 'NFT Sahibi',
    'quest.nftHoldingDesc': 'Bonus puan kazanmak için özel NFT\'mizi tutun',
    'quest.points': 'puan',
    'quest.claim': 'Al',
    'quest.locked': 'Kilitli',
    'quest.inProgress': 'Devam Ediyor',
    'quest.connectWallet': 'Cüzdanınızı Bağlayın',
    'quest.connectWalletDesc': 'Puan kazanmaya ve görevleri tamamlamaya başlamak için cüzdanınızı bağlayın!',
    'quest.dailyCheckInComplete': 'Günlük Giriş Tamamlandı!',
    'quest.questCompleted': 'Görev Tamamlandı! 🎉',
    'quest.questFailed': 'Görev Başarısız',
    'quest.earnedPoints': '{points} puan kazandınız!',
    'quest.dailyCast': 'Günlük Cast',
    'quest.dailyCastDesc': 'Farcaster\'a içerik yayınla ve puan kazan',
    'quest.totalCast': 'Toplam Cast',
    'quest.sendGmDaily': 'Günlük GM Gönder',
    'quest.sendGmDailyDesc': 'GMonchain miniapp\'ini aç ve GM\'ini başka bir zincire gönder!',
    'quest.castNow': 'Şimdi Cast\'le 📡',
    'quest.nextCheckIn': 'Sonraki giriş',
    'quest.shareApp': 'ContentCastAI\'ı Paylaş',
    'quest.shareAppDesc': '🚀 Kaliteli içerikler paylaşın ve günlük görevleri tamamlayarak ödüller kazanın!',
    'quest.shareNow': 'Şimdi Paylaş 🎉',
    'quest.bonusQuests': 'Bonus Görevler',
    'quest.bonusQuestsDesc': 'Ekstra puan kazanmak için tek seferlik bonus görevler',
    'quest.followFarcaster': 'Farcaster\'da Takip Et',
    'quest.followFarcasterDesc': 'Farcaster\'da @mrrobotcrypto.eth\'i takip edin',
    'quest.followX': 'X\'de Takip Et',
    'quest.followXDesc': 'X (Twitter)\'da @MrRobotKripto\'yu takip edin',
    'quest.addMiniApp': 'Mini App Ekle',
    'quest.addMiniAppDesc': 'ContentCastAI\'ı uygulama listenize ekleyin',
    'quest.follow': 'Takip Et',
    'quest.addToApps': 'Uygulamalara Ekle',
    'quest.completeTask': 'Görevi Tamamla',
    'quest.progress': 'İlerleme',
    'quest.oneTimeQuests': 'Tek Seferlik Görevler',
    'quest.addNow': 'Şimdi Ekle',
    'quest.walletRequired': 'Cüzdan Gerekli',
    'leaderboard.title': 'Liderlik Tablosu',
    'leaderboard.subtitle': 'Diğer kullanıcılarla yarışın ve zirveye tırmanın',
    'leaderboard.weekly': '7 Gün',
    'leaderboard.monthly': '1 Ay',
    'leaderboard.quarterly': '3 Ay',
    'leaderboard.yearly': '1 Yıl',
    'leaderboard.yourPosition': 'Sizin Pozisyonunuz',
    'leaderboard.points': 'puan',
    'leaderboard.topPlayers': 'En İyi Oyuncular',
    'leaderboard.fullRankings': 'Tam Sıralama',
    'leaderboard.user': 'Kullanıcı',
    'leaderboard.weeklyPoints': 'Bu Hafta',
    'leaderboard.dailyStreak': 'Günlük Seri',
    'leaderboard.dailyCasts': 'Günlük Cast',
    'leaderboard.completed': 'Tamamlandı',
    'leaderboard.casts': 'cast',
    'leaderboard.quests': 'görev',
    'rewards.title': 'Kazançlarım',
    'rewards.subtitle': 'Quest puanlarınıza göre kazandığınız DEGEN tokenlerini claim edin',
    'rewards.connectWallet': 'Cüzdanınızı Bağlayın',
    'rewards.connectWalletDesc': 'DEGEN ödüllerinizi görüntülemek ve claim etmek için cüzdanınızı bağlayın!',
    'rewards.totalPoints': 'Toplam Puan',
    'rewards.claimableDegen': 'Claim Edilebilir DEGEN',
    'rewards.degenPerPoint': 'Puan Başına DEGEN',
    'rewards.degenClaim': 'DEGEN Token Claim',
    'rewards.howItWorks': 'Nasıl çalışır:',
    'rewards.rule1': '1 Quest Puanı = 0.1 DEGEN Token',
    'rewards.rule2': 'Claim etmek için minimum 250 puan gerekli',
    'rewards.rule3': 'Biriken tüm DEGEN\'inizi tek seferde claim edin',
    'rewards.rule4': 'Claim ettikten sonra puanlar sıfırlanır',
    'rewards.readyToClaim': '{amount} DEGEN token claim edebilirsiniz!',
    'rewards.needMorePoints': 'DEGEN claim etmek için {amount} puan daha gerekli',
    'rewards.completeQuests': 'Daha fazla puan kazanmak için günlük görevleri tamamlayın!',
    'rewards.progress': 'Sonraki Claim\'e Kadar İlerleme',
    'leaderboard.streak': 'Seri',
    'leaderboard.days': 'gün',
    'leaderboard.you': 'Sen',
    'leaderboard.connectWallet': 'Cüzdanınızı Bağlayın',
    'leaderboard.connectWalletDesc': 'Liderlik tablosundaki pozisyonunuzu görmek için cüzdanınızı bağlayın!',
    'leaderboard.share': 'Pozisyonu Paylaş',
    'leaderboard.sharing': 'Paylaşılıyor...',
    'leaderboard.previous': 'Önceki',
    'leaderboard.next': 'Sonraki',
    'header.feedback': 'Geri Bildirim',
    'menu.goToAbout': 'ContentCastAI Hakkında Daha Fazla Bilgi',
    'menu.sendFeedback': 'Geri Bildirim Gönder',
    'about.title': 'ContentCastAI Hakkında',
    'about.subtitle': 'Merkeziyetsiz sosyal web için AI destekli içerik oluşturma',
    'about.what.title': 'ContentCastAI Nedir?',
    'about.what.desc1': 'ContentCastAI, yapay zekanın gücünü merkezi olmayan sosyal ağ Farcaster ile birleştiren yenilikçi bir platformdur. Misyonumuz, yaratıcılar, pazarlamacılar ve günlük kullanıcıların ilgi çekici, yüksek kaliteli içerik üretmelerini zahmetsizce sağlamaktır.',
    'about.what.desc2': 'AI destekli içerik üretimi, düzenlenmiş stok fotoğraf entegrasyonu, görevler ve liderlik tabloları ile oyunlaştırma ve çok dilli destek gibi özelliklerle ContentCastAI, içerik oluşturmayı herkes için erişilebilir ve eğlenceli hale getirir.',
    'about.features.title': 'Temel Özellikler',
    'about.feature1.title': 'AI Destekli İçerik',
    'about.feature1.desc': 'Gelişmiş AI teknolojisi ile ilgi çekici sosyal medya içeriği üretin',
    'about.feature2.title': 'Farcaster Entegrasyonu',
    'about.feature2.desc': 'İçeriğinizi merkeziyetsiz sosyal ağa sorunsuzca yayınlayın',
    'about.feature3.title': 'Görev Sistemi',
    'about.feature3.desc': 'Puan kazanın, serileri koruyun ve liderlik tablosunda yükselinn',
    'about.developer.title': 'Geliştirici',
    'about.developer.desc': 'ContentCastAI, Web3, merkeziyetsiz sosyal ağlar ve AI teknolojisine duyulan tutkuyla geliştirildi. Sosyal medyanın yeni çağında yaratıcıları güçlendirmek için inşa edildi.',
    'about.connect': 'Geliştirici ile İletişim:',
    'about.tech.title': 'Teknoloji Yığını',
    'about.version': 'Sürüm',
    'about.builtWith': 'İle yapıldı',
    'about.forWeb3': 'Web3 topluluğu için',
    'about.copied': 'Panoya kopyalandı!',
    'about.copiedDesc': 'başarıyla kopyalandı',
    'about.copyFailed': 'Kopyalama başarısız',
    'about.copyFailedDesc': 'Lütfen manuel olarak kopyalayın',
    'countdown.resetIn': 'Reset süresi',
    'countdown.resetAvailable': 'Reset mevcut!',
    'wallet.balances': 'Bakiyeler',
    'home.recentActivity': 'Son Aktiviteler',
    'home.shareApp': 'ContentCastAI\'ı Paylaş',
    'home.shareAppDesc': 'Uygulamayı paylaşarak günlük 1 puan kazan',
    'about.donate.title': 'Projeyi Destekleyin',
    'about.donate.desc': 'ContentCastAI\'yi geliştirmeye devam etmemize şu adrese bağış yaparak yardımcı olun:',
    'about.donate.address': 'mrrobotcrypto.eth',
    'feedback.title': 'Geri Bildirim',
    'feedback.subtitle': 'Düşüncelerinizi paylaşarak, hata bildirerek veya yeni özellikler önererek ContentCastAI\'yi geliştirmemize yardımcı olun',
    'feedback.typeLabel': 'Geri Bildirim Türü',
    'feedback.typePlaceholder': 'Geri bildirim türü seçin...',
    'feedback.messageLabel': 'Mesajınız',
    'feedback.messagePlaceholder': 'Lütfen geri bildiriminizi detaylı bir şekilde açıklayın. Herhangi bir sorun, öneri veya beğendikleriniz hakkında spesifik olun...',
    'feedback.minLength': 'Minimum 10 karakter',
    'feedback.send': 'Geri Bildirim Gönder',
    'feedback.sending': 'Gönderiliyor...',
    'feedback.success': 'Geri Bildirim Gönderildi!',
    'feedback.successDesc': 'Geri bildiriminiz için teşekkür ederiz. Katkınızı takdir ediyoruz!',
    'feedback.error': 'Hata',
    'feedback.errorDesc': 'Geri bildirim gönderilemedi. Lütfen tekrar deneyin.',
    'feedback.typeRequired': 'Geri Bildirim Türü Gerekli',
    'feedback.typeRequiredDesc': 'Lütfen bir geri bildirim türü seçin',
    'feedback.messageRequired': 'Mesaj Gerekli',
    'feedback.messageRequiredDesc': 'Lütfen geri bildirim mesajınızı girin',
    'feedback.messageTooShort': 'Mesaj Çok Kısa',
    'feedback.messageTooShortDesc': 'Lütfen daha detaylı geri bildirim sağlayın (en az 10 karakter)',
    'feedback.thankYou': 'Teşekkür Ederiz!',
    'feedback.thankYouDesc': 'Geri bildiriminiz başarıyla gönderildi. Katkınızı gerçekten takdir ediyoruz ve dikkatli bir şekilde inceleyeceğiz.',
    'feedback.sendMore': 'Daha Fazla Geri Bildirim Gönder',
    'feedback.types.bug': 'Hata Raporu',
    'feedback.types.bugDesc': 'Bir sorun veya hata bildirin',
    'feedback.types.feature': 'Özellik İsteği',
    'feedback.types.featureDesc': 'Yeni bir özellik veya iyileştirme önerin',
    'feedback.types.general': 'Genel Geri Bildirim',
    'feedback.types.generalDesc': 'Düşüncelerinizi veya önerilerinizi paylaşın',
    'feedback.types.compliment': 'İltifat',
    'feedback.types.complimentDesc': 'Uygulamada beğendiklerinizi paylaşın',
    'feedback.guidelines.title': 'Geri Bildirim Rehberi',
    'feedback.guidelines.bugs': 'Hata Raporları:',
    'feedback.guidelines.bugsDesc': 'Lütfen sorunu yeniden oluşturmak için detaylı adımları ve tarayıcı bilgilerinizi ekleyin.',
    'feedback.guidelines.features': 'Özellik İstekleri:',
    'feedback.guidelines.featuresDesc': 'Özelliğin size ve diğer kullanıcılara nasıl fayda sağlayacağını açıklayın.',
    'feedback.guidelines.general': 'Genel Geri Bildirim:',
    'feedback.guidelines.generalDesc': 'Genel deneyiminizi ve iyileştirme önerilerinizi paylaşın.'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('farcastai-language') || 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('farcastai-language', lang);
    }
  };

  const t = (key: string): string => {
    const translation = translations[language as keyof typeof translations];
    return translation?.[key as keyof typeof translation] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}